### ISSUE TITLE
Collectiosn requirements file missing

### ISSUE THREAD

**Issue by uk-bolly** [ansible-lockdown/AMAZON2-CIS#1]
**Describe the Issue**

If using ansible-core not all the modules are included

**Expected Behavior**
collections/requirements.yml should specify what is needed along with the meta file stating the other collectons that are needed.

**Actual Behavior**
fails due to missing modules when using ansible core

**Control(s) Affected**
1.6.1,3,4,5

**Environment (please complete the following information):**

All

Anything additional goes here

**Possible Solution**
Add collections correctly

**Comment by andrew-aiken** [comment]
Created a [PR](https://github.com/ansible-lockdown/AMAZON2-CIS/pull/2) adding the change.

**Comment by andrew-aiken** [comment]
Resolved in latest PR
