### ISSUE TITLE
/opt/AMAZON2-CIS-Audit/run_audit.sh: Permission denied

### ISSUE THREAD

**Issue by swestcott** [ansible-lockdown/AMAZON2-CIS#19]
**Describe the Issue**
As per #18, I'm running in an environment without internet access so I need to copy the audit file to the server.

Relevant config,
```
    setup_audit: true
    run_audit: true
    skip_reboot: true
    get_goss_file: copy
    audit_content: copy
    copy_goss_from_path: ../goss
    audit_local_copy: ../AMAZON2-CIS-Audit/
```

**Expected Behavior**
Ansible is able to execute the run_audit.sh script

**Actual Behavior**
run_audit.sh fails to run as it's missing the execute bit

```
fatal: [default]: FAILED! => {"changed": true, "cmd": "/opt/AMAZON2-CIS-Audit/run_audit.sh -v /opt/AMAZON2-CIS-Audit/vars/ip-10-0-0-8.yml -o /opt/ip-10-0-0-8-AMAZON2-CIS_pre_scan_1682517307.json -g ['ungrouped']", "delta": "0:00:00.003543", "end": "2023-04-26 14:06:20.355328", "msg": "non-zero return code", "rc": 126, "start": "2023-04-26 14:06:20.351785", "stderr": "/bin/sh: /opt/AMAZON2-CIS-Audit/run_audit.sh: Permission denied", "stderr_lines": ["/bin/sh: /opt/AMAZON2-CIS-Audit/run_audit.sh: Permission denied"], "stdout": "", "stdout_lines": []}
```

**Environment (please complete the following information):**
As per #18

**Additional Notes**
When the Audit files are copied to the remote host, the file permissions are set to 0644, thereby removing the execute bit(s) on all files, including run_audit.sh

https://github.com/ansible-lockdown/AMAZON2-CIS/blob/devel/tasks/pre_remediation_audit.yml#L33-L39

**Possible Solution**
Either preserve or re-add the execute bit on run_audit.sh

**Comment by uk-bolly** [comment]
hi @swestcott 

Many thanks for raising this issue, I am happy to include in the next PR to devel. hopefully to be merged later this week.

regards

uk-bolly
